Update docker base image & respect sonar-project.properties
kitabisa/sonarqube-action pull request #20
Opened 2020-12-17 23:36 UTC by jankal

### Description
As the title says, I updated the base image this image relies on so it now ueses SonarScanner v4.5. The image size might be accacted. I think, this is a non-issue bc GitHub handles pulling the image.  
I also added logic to detect a `sonar-project.properties` file in the current directory. When one is present the config settings from that file are used instead of settings from GH Actions or auto-generated settings (like `projectName` being the repo name).

### Related Issue
Fixes #5
Also updates Docker base image to Sonar-Scanner v4.5

### Motivation and Context
The upstream docker image already dates back one year. I also hope to get rid of the node:8 warnings in SonarQube.

### Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] ~New feature (non-breaking change which adds functionality)~
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

### How Has This Been Tested?
I ran the action in one of my projects, where a `sonar-project.properties` file exists.

See [here](https://github.com/jankal/jankal.dev/runs/1573645255?check_suite_focus=true).

2020-12-18 00:01 UTC, dwisiswant0 commented
Noice, @jankal! :fire:
We'll go back as soon for review.

2020-12-18 04:32 UTC, dwisiswant0 requested changes

2020-12-18 04:32 UTC, dwisiswant0 commented on entrypoint.sh
> +then
I also think what if we replace the base directory with the environment variable `GITHUB_WORKSPACE`? Like: `"${GITHUB_WORKSPACE}/sonar-project.properties"`.

2020-12-19 21:36 UTC, dwisiswant0 approved these changes

2020-12-19 21:37 UTC, dwisiswant0 commented
Hi, @jankal. Is c949545 passed test?

2020-12-19 23:08 UTC, jankal commented
@dwisiswant0 thank you for checking back again. I found issues on line 17 of `entrypoint.sh` which I have to fix first. Do not merge.

2020-12-19 23:15 UTC, jankal commented
@dwisiswant0 now I think it's all fixed up :)

2020-12-29 02:55 UTC, merged