feat: Rerun scan on PR edited, reopened and synchronize
kitabisa/sonarqube-action pull request #26
Opened 2021-06-07 12:22 UTC by rthewhite

THIS PROJECT IS IN MAINTENANCE MODE. We accept pull-requests for Bug Fixes **ONLY**. NO NEW FEATURES ACCEPTED!

---

### Description
Currently scan is not being run on any other event on a pull request other then opened. Ideally you want to re-run when changes are being made, when it gets reopened or synchronises.

### Related Issue
https://github.com/kitabisa/sonarqube-action/issues/21

Fixes #
- Run on pull request edit
- Run on pull request reopened
- Run on pull request synchronize

### Motivation and Context
It fixes the problem that when a developer makes changes to fix issues reported by SonarQube for this PR that a new scan is triggered.

https://github.com/kitabisa/sonarqube-action/issues/21

### Types of Changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] ~New feature (non-breaking change which adds functionality)~
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

### How Has This Been Tested?

### Screenshots (if appropriate):

2021-06-09 04:16 UTC, dwisiswant0 requested changes

2021-06-09 04:16 UTC, dwisiswant0 commented on entrypoint.sh
> +	if [[ "${EVENT_ACTION}" != "opened" && "${EVENT_ACTION}" != "edited" && "${EVENT_ACTION}" != "reopened" && "${EVENT_ACTION}" != "synchronize"  ]]; then
I think here should use logical OR instead of AND.

2021-06-10 08:32 UTC, rthewhite commented on entrypoint.sh
> +	if [[ "${EVENT_ACTION}" != "opened" && "${EVENT_ACTION}" != "edited" && "${EVENT_ACTION}" != "reopened" && "${EVENT_ACTION}" != "synchronize"  ]]; then
No it should be AND since it's a negated check. Imagine using OR and the event action type is edited, then the first check: `EVENT_ACTION != opened` is already true and it goes into this if statement not running the scan where as we want it to scan for opened, edited or synchronize. 

Using OR would make the behaviour depend on the order of the checks making it only work for the first one.

2021-06-16 05:21 UTC, dwisiswant0 commented
Please make sure all new and existing tests pass so we can get past the review stage.

2021-06-21 08:52 UTC, rthewhite commented
Sorry for the late reply i had some time off. Can you explain to me which tests to run and how? 
I have probably overlooked it but i don't see any tests or any instructions in the repository on how to run tests?

2022-06-16 05:38 UTC, dwisiswant0 commented
Since v1.2.0, this action accepts any triggering event.

2022-06-16 05:38 UTC, closed without merging